# Generated by Django 6.1.1 on 2026-09-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('catalog', '0001_initial'),
        ('orders', '0002_orderitem_reservation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='orders_item_matches_type',
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('beat_license__isnull', False), ('item_type', 'beat_license'), ('reservation__isnull', True), ('service_product__isnull', True)), models.Q(('beat_license__isnull', True), ('item_type', 'service'), ('reservation__isnull', True), ('service_product__isnull', False)), models.Q(('beat_license__isnull', True), ('item_type', 'booking'), ('reservation__isnull', False), ('service_product__isnull', True)), _connector='OR'), name='orders_item_matches_type'),
        ),
    ]
