# Generated by Django 6.1.1 on 2026-10-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_reservation_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('checkout_completed', 'Checkout completed'), ('amount_mismatch', 'Paid amount mismatch'), ('checkout_expired', 'Checkout expired'), ('payment_failed', 'Payment failed'), ('refund', 'Refund'), ('ignored', 'Ignored event')], max_length=30),
        ),
    ]
