# Generated by Django 6.1.1 on 2026-09-27 16:25

import apps.core.storage
import apps.services.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('awaiting_files', 'Awaiting files'), ('received', 'Files received'), ('in_progress', 'In progress'), ('delivered', 'Delivered'), ('revision_requested', 'Revision requested'), ('completed', 'Completed')], db_index=True, default='awaiting_files', max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Customer brief: references, loudness, vibe.')),
                ('reference_links', models.TextField(blank=True)),
                ('revisions_used', models.PositiveSmallIntegerField(default=0)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='service_order', to='orders.orderitem')),
                ('service_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='catalog.serviceproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('customer_upload', 'Customer upload'), ('studio_deliverable', 'Studio deliverable')], max_length=30)),
                ('file', models.FileField(max_length=500, storage=apps.core.storage.private_storage, upload_to=apps.services.models.service_file_path)),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('round', models.PositiveSmallIntegerField(default=0, help_text='0 = original delivery, 1+ = revision rounds')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='services.serviceorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='services.serviceorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
