# Generated by Django 6.1.1 on 2026-09-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_kind', models.CharField(choices=[('mp3', 'MP3'), ('wav', 'WAV'), ('stems', 'Stems (ZIP)')], max_length=10)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('max_downloads', models.PositiveIntegerField(default=10)),
                ('expires_at', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order_item', 'file_kind'],
            },
        ),
    ]
