# Generated by Django 6.1.1 on 2026-09-27 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('downloads', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadgrant',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_grants', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='downloadgrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='downloadgrant',
            constraint=models.UniqueConstraint(fields=('order_item', 'file_kind'), name='downloads_one_grant_per_kind'),
        ),
    ]
