# Generated by Django 6.1.1 on 2026-09-27 16:34

import django.contrib.postgres.constraints
import django.contrib.postgres.operations
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # `session_date WITH =` inside the exclusion constraint needs btree_gist.
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('artist_name', models.CharField(blank=True, max_length=100)),
                ('service_type', models.CharField(choices=[('recording', 'Recording'), ('mixing', 'Mixing session'), ('mastering', 'Mastering session'), ('beat', 'Beat production'), ('vocal', 'Vocal production')], max_length=20)),
                ('session_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('duration_hours', models.PositiveSmallIntegerField(choices=[(1, '1 h'), (2, '2 h'), (4, '4 h'), (8, '8 h')])),
                ('slot', django.contrib.postgres.fields.ranges.IntegerRangeField(editable=False)),
                ('project_description', models.TextField(blank=True)),
                ('reference_links', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('hold', 'Held (awaiting payment)'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('expired', 'Expired (unpaid)')], db_index=True, default='hold', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('locale', models.CharField(default='en', max_length=5)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-session_date', '-start_time'],
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ('hold', 'confirmed'))), expressions=[('session_date', '='), ('slot', '&&')], name='bookings_no_overlap')],
            },
        ),
    ]
