# Generated by Django 6.1.1 on 2026-09-27 15:54

import apps.core.storage
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('kind', models.CharField(choices=[('mastering', 'Mastering'), ('mixing', 'Mixing')], max_length=20)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('turnaround_days', models.PositiveSmallIntegerField(default=5)),
                ('included_revisions', models.PositiveSmallIntegerField(default=1)),
                ('max_stems', models.PositiveSmallIntegerField(default=1, help_text='How many source files the customer may upload.')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'price_usd'],
            },
        ),
        migrations.CreateModel(
            name='StudioRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(choices=[('recording', 'Recording'), ('mixing', 'Mixing session'), ('mastering', 'Mastering session'), ('beat', 'Beat production'), ('vocal', 'Vocal production')], max_length=20, unique=True)),
                ('hourly_price_usd', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['service_type'],
            },
        ),
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('bpm', models.PositiveSmallIntegerField()),
                ('key', models.CharField(blank=True, help_text='Musical key, e.g. Am, F#m, C', max_length=8)),
                ('genre', models.CharField(blank=True, max_length=60)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, storage=apps.core.storage.public_storage, upload_to='beats/covers/')),
                ('preview', models.FileField(blank=True, help_text='Tagged MP3 played on the storefront.', storage=apps.core.storage.public_storage, upload_to='beats/previews/')),
                ('duration_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('sold_exclusive', 'Sold (exclusive)')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='catalog_bea_status_5a5134_idx'), models.Index(fields=['genre'], name='catalog_bea_genre_5edad3_idx')],
            },
        ),
        migrations.CreateModel(
            name='BeatLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('mp3_lease', 'MP3 Lease'), ('wav_lease', 'WAV Lease'), ('trackout', 'Trackout (stems)'), ('exclusive', 'Exclusive')], max_length=20)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('terms', models.TextField(blank=True, help_text='License terms shown before purchase.')),
                ('mp3_file', models.FileField(blank=True, storage=apps.core.storage.private_storage, upload_to='beats/files/')),
                ('wav_file', models.FileField(blank=True, storage=apps.core.storage.private_storage, upload_to='beats/files/')),
                ('stems_zip', models.FileField(blank=True, storage=apps.core.storage.private_storage, upload_to='beats/files/')),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='catalog.beat')),
            ],
            options={
                'ordering': ['price_usd'],
                'constraints': [models.UniqueConstraint(fields=('beat', 'tier'), name='catalog_one_license_per_tier')],
            },
        ),
    ]
