# Generated by Django 6.1.1 on 2026-09-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='description_tr',
            field=models.TextField(blank=True, help_text='Turkish description; falls back to English.'),
        ),
        migrations.AddField(
            model_name='serviceproduct',
            name='description_tr',
            field=models.TextField(blank=True, help_text='Turkish description; falls back to English.'),
        ),
        migrations.AddField(
            model_name='serviceproduct',
            name='name_tr',
            field=models.CharField(blank=True, help_text='Turkish name; falls back to name.', max_length=120),
        ),
    ]
